version: '3.8'
services:
  prometheus:
    build: ./prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus-data:/prometheus

  grafana:
    build: ./grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  prometheus-data:
  grafana-data: